name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

env:
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PACKAGE_NAME: aws-iot-device-sdk-python
  AWS_EC2_METADATA_DISABLED: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Unit tests
        run: |
          python3 setup.py install
          pip install pytest
          pip install mock
          python3 -m pytest test

